name: airship_carrier
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.5
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.24
  country_flags: ^3.2.0
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  camera: ^0.11.1
  dotted_line: ^3.2.2
  flutter_image_compress: ^2.1.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  fluttertoast: ^8.2.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.3
  dio: ^5.8.0+1
  shared_preferences: ^2.2.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  package_info_plus: ^8.0.0
  flutter_plugin_android_lifecycle: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-VariableFont.ttf
        - asset: assets/fonts/NotoSans-Italic-VariableFont.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Carriers.png"
  adaptive_icon_background: "#ffffff" # or an image path
  adaptive_icon_foreground: "assets/images/Carriers.png"

dependency_overrides:
  win32: ^5.13.0

