name: airshipxp_shipper
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  http: ^1.2.1
  dio: ^4.0.6
  country_list_pick: ^1.0.1+6
  fluttertoast: ^8.2.1
  get: ^4.6.5
  get_it: any
  sqflite: ^2.3.0
  google_places_flutter: ^2.0.6
  location: ^5.0.3
  geocoding: ^2.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  flutter_image_compress: ^2.1.0
  image_picker: ^1.0.5
  intl: ^0.19.0
  url_launcher: ^6.3.0
  url_launcher_ios: ^6.3.3
  permission_handler: ^11.0.1
  package_info_plus: ^8.0.0
  cupertino_icons: ^1.0.2
  flutter_stripe: ^10.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  win32: ^5.12.0
  flutter_plugin_android_lifecycle: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  otp_text_field: ^1.1.3
  smooth_page_indicator: ^1.1.0
  camera: ^0.10.5+6
  dotted_line: ^3.2.2
  table_calendar: ^3.0.9
  pin_code_fields: ^8.0.1
  sizer: ^2.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Shippers.png"
  adaptive_icon_background: "#ffffff" # or an image path
  adaptive_icon_foreground: "assets/images/Shippers.png"
